services:
  decypharr:
    image: cy01/blackhole:latest
    container_name: decypharr
    restart: ${RESTART_POLICY}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH}/decypharr:/app
      - ${DATA_PATH}/decypharr/mnt:/mnt:rshared
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true
